# Generated by Django 3.2.6 on 2021-09-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210905_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleSection',
        ),
    ]
