# Generated by Django 3.2.6 on 2021-09-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_delete_articlesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='article.articlebar'),
        ),
    ]
